### ISSUE TITLE
PDM Playground

### ISSUE THREAD

**Issue by j054n** [bradhowes/keystrokecountdown#1]
Hi Mr Howes,
I have read your work about PDM and the references you propose and also testing your scripts, because I am involved in a similar work. I congratulate you for your work, I have learned a lot.
I would like to ask you about this, in the sense of testing with high-frequencies, if you have obtained similar results with the needed for PDM mics, I have tried to do it with 3.072 MHz and decimation of 32 to obtain a PCM signal at 96 KHz filtering in 16 KHz, but when I obtain FFT plot the magnitude of objective freq (16 KHz) appears but is too low and also appears another freq (32 KHz) with the half of previous magnitude.
I don't know if I have not procceded right because I have tested with several filters and always appears this alias, and I don't understand either because you tuned the filter with 2.048 KHz and not with 1.024 KHz and a decimation factor of 64.
If you could help me, I would be very grateful.
Thanks in advance and best grettings.

**Comment by bradhowes** [comment]
Hi, sorry for the long delay in replying. I just saw the issue count at 1 and was curious so I looked.

Sorry I can't be much help here. I have never used an actual PDM mic, so I tried to sort of simulate one. This was for a project of a friend who was going to use a pair of them for stereo sound, but he did not have a driver for them. This was several years ago, so now my recollection of the math and details are a bit fuzzy with time.

So the decimation I *think* is based on the fact that was working in the low frequency domain for simplicity (512 Hz -- 1024 Hz to remove any aliasing). Since the PDM device uses a 65.536 kHz, decimating by selecting 1 out of 64 bits will get us down to 1024 Hz. I don't recall why I went for 32x decimation and a low-pass filter attenuating at 2.048 kHz. Probably got confused with my terms.

As to your issue, I can only guess that there is a mismatch between the samples from your device and what you are modeling. I hope you were able to figure it out.
